name: NodeJS SAST

on:
  workflow_call:

jobs:
  sast-scans:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup python image
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install NodeJSScan
      run: |
        pip install nodejsscan
    - name: Run NodeJSScan
      run: |
        echo GITHUBWORKSPACE=$GITHUB_WORKSPACE
        nodejsscan -d $GITHUB_WORKSPACE
