name: Centralized Workflows - Publish image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
#     secrets:
#       registry_username:
#         required: true
#       registry_password:
#         required: true

jobs:
  publish:
    runs-on: ubuntu-latest
#     needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_USERNAME }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        push: true
        tags: ${{ inputs.image_name }}:${{ inputs.tag }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
